import { primitiveTokens } from './primitives';

const {
  color,
  shadows,
  gradient,
  borderRadius,
  borderWidth,
  linearSpacing,
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
  breakpoint,
  layout,
} = primitiveTokens;

export const semanticTokens = {
  color: {
    background: {
      default: color['gray-10'],
      subtle: color['gray-20'],
      disabled: color['gray-30'],
      success: color['emerald-10'],
      successHover: color['emerald-20'],
      successPressed: color['emerald-30'],
      accent: color['emerald-60'],
      accentHover: color['emerald-70'],
      accentPressed: color['emerald-80'],
      errorSubtle: color['red-20'],
      errorSubtleHover: color['red-30'],
      errorSubtlePressed: color['red-40'],
      error: color['red-60'],
      errorHover: color['red-70'],
      errorPressed: color['red-80'],
      warning: color['orange-10'],
      info: color['blue-10'],
    },
    text: {
      invert: color['gray-10'],
      heading: color['gray-80'],
      default: color['gray-70'],
      accent: color['emerald-60'],
      hover: color['emerald-70'],
      pressed: color['emerald-80'],
      disabledSubtle: color['gray-40'],
      disabled: color['gray-60'],
      error: color['red-60'],
      warning: color['orange-90'],
      success: color['green-70'],
      info: color['blue-50'],
    },
    border: {
      focusOffset: color['gray-10'],
      subtle: color['gray-70'],
      default: color['gray-80'],
      disabled: color['gray-30'],
      hover: color['emerald-50'],
      pressed: color['emerald-80'],
      accent: color['emerald-60'],
      success: color['green-70'],
      divider: color['emerald-20'],
      focusInfo: color['blue-50'],
      warning: color['orange-90'],
      error: color['red-60'],
      errorHover: color['red-70'],
      errorPressed: color['red-80'],
    },
    icon: {
      invert: color['gray-10'],
      default: color['gray-80'],
      accent: color['emerald-60'],
      hover: color['emerald-70'],
      pressed: color['emerald-80'],
      disabledSubtle: color['gray-40'],
      disabled: color['gray-60'],
      success: color['green-70'],
      error: color['red-60'],
      info: color['blue-50'],
      warning: color['orange-90'],
    },
  },
  shadow: {
    sm: shadows.sm,
    md: shadows.md,
    lg: shadows.lg,
    inner: shadows.inner,
    header: shadows.header,
    dropdown: shadows.dropdown,
  },
  gradient: {
    primary: gradient.primary,
    subtle: gradient.subtle,
    secondary: gradient.secondary,
  },
  borderRadius: {
    none: borderRadius.none,
    xs: borderRadius.xs,
    sm: borderRadius.sm,
    md: borderRadius.md,
    lg: borderRadius.lg,
    pill: borderRadius.pill,
    circle: borderRadius.circle,
  },
  borderWidth: {
    none: borderWidth.none,
    sm: borderWidth.sm,
    md: borderWidth.md,
    lg: borderWidth.lg,
    xl: borderWidth.xl,
  },
  spacing: {
    none: linearSpacing['spacing-none'],
    x4xs: linearSpacing['spacing-4-xs'],
    x3xs: linearSpacing['spacing-3-xs'],
    x2xs: linearSpacing['spacing-2-xs'],
    xs: linearSpacing['spacing-xs'],
    s: linearSpacing['spacing-s'],
    m: linearSpacing['spacing-m'],
    l: linearSpacing['spacing-l'],
    xl: linearSpacing['spacing-xl'],
    x2xl: linearSpacing['spacing-2-xl'],
    x3xl: linearSpacing['spacing-3-xl'],
    layout: {
      l: linearSpacing['spacing-layout-l'],
      xl: linearSpacing['spacing-layout-xl'],
      x2xl: linearSpacing['spacing-layout-2-xl'],
    },
  },
  typography: {
    headline: {
      xl: {
        fontSize: fontSize['48'],
        fontWeight: fontWeight.bold,
        lineHeight: lineHeight.tight,
      },
      lg: {
        fontSize: fontSize['40'],
        fontWeight: fontWeight.bold,
        lineHeight: lineHeight.tight,
      },
      base: {
        fontSize: fontSize['32'],
        fontWeight: fontWeight.bold,
        lineHeight: lineHeight.tight,
      },
      sm: {
        fontSize: fontSize['24'],
        fontWeight: fontWeight.regular,
        lineHeight: lineHeight.normal,
      },
      smHigh200: {
        fontSize: fontSize['24'],
        fontWeight: fontWeight.bold,
        lineHeight: lineHeight.normal,
      },
    },
    text: {
      xlHigh200: {
        fontSize: fontSize['18'],
        fontWeight: fontWeight.bold,
        lineHeight: lineHeight.normal,
      },
      xl: {
        fontSize: fontSize['18'],
        fontWeight: fontWeight.regular,
        lineHeight: lineHeight.normal,
      },
      base: {
        fontSize: fontSize['16'],
        fontWeight: fontWeight.regular,
        lineHeight: lineHeight.normal,
      },
      baseHigh200: {
        fontSize: fontSize['16'],
        fontWeight: fontWeight.bold,
        lineHeight: lineHeight.normal,
      },
      sm: {
        fontSize: fontSize['14'],
        fontWeight: fontWeight.regular,
        lineHeight: lineHeight.normal,
      },
      smHigh200: {
        fontSize: fontSize['14'],
        fontWeight: fontWeight.semibold,
        lineHeight: lineHeight.normal,
      },
      xs: {
        fontSize: fontSize['12'],
        fontWeight: fontWeight.regular,
        lineHeight: lineHeight.normal,
      },
      xsHigh200: {
        fontSize: fontSize['12'],
        fontWeight: fontWeight.bold,
        lineHeight: lineHeight.normal,
      },
    },
  },
  fontFamily: {
    body: fontFamily.body,
    heading: fontFamily.heading,
  },
  fontWeight: {
    regular: fontWeight.regular,
    semibold: fontWeight.semibold,
    bold: fontWeight.bold,
    extra: fontWeight.extra,
  },
  breakpoints: {
    sm: breakpoint.sm,
    md: breakpoint.md,
    lg: breakpoint.lg,
    xl: breakpoint.xl,
  },
  layout: {
    maxWidth: layout.maxWidth,
  },
} as const;
